name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  Unit_testing:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f .tests/unit/requirements.txt ]; then pip install -r .tests/unit/requirements.txt; fi
    
    - name: Unit testing
      run: |
        pytest .tests/unit
    
    - name: Cancelling parallel jobs
      if: failure()
      uses: andymckay/cancel-action@0.3

  Integration_testing:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Integration testing
      uses: snakemake/snakemake-github-action@v1.24.0
      with:
        directory: '.tests/integration'
        snakefile: 'workflow/Snakefile'
        args: "--cores 1 --use-conda --conda-cleanup-pkgs cache --conda-prefix envs --show-failed-logs --configfile .tests/integration/config/config.yaml"
        stagein: |
            conda config --set channel_priority strict
